/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cenxui' at '11/18/16 2:03 PM' with Gradle 2.14.1
 *
 * @author cenxui, @date 11/18/16 2:03 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
